### ISSUE TITLE
Add viewer on audio call

### ISSUE THREAD

**Issue by varunsdcet** [dipeshdulal/webrtc-antmediaserver#1]
How we add viewer in call

**Comment by dipeshdulal** [comment]
It is just a demo for live streaming video. (Not video calling)
There is viewer section in the menu and publisher section in the menu. You will need two devices for testing. 

I guess, If you want to do video calling you will need a different setup.
For signaling; 
https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Details

This might be a starting point.

Sorry for this late reply. 🙇

**Comment by dipeshdulal** [comment]
There is also test code for conference call. 
Not the way ant media does it but uses same approach as video calling with multiple webrtc connections. 

https://github.com/dipeshdulal/webrtc-antmediaserver/tree/feat/conference
