### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by rehamkhawajahere** [dipeshdulal/webrtc-antmediaserver#2]
Can you give example how Media URL should look like. I am running Ant media server on EC2 instance and its running as I can see the web panel of ant media server but how can i stream to Ant media server?

**Comment by dipeshdulal** [comment]
Configuration URL should look like; 
```js
export const config = {
    SIGNALING_URL: "ws://<server-domain>:5080/WebRTCAppEE/websocket"
}
```

They are used when instantiating the signaling server. 
https://github.com/dipeshdulal/webrtc-antmediaserver/blob/master/Publisher.tsx#L61

For stream id of live streaming I have used static stream id. 
https://github.com/dipeshdulal/webrtc-antmediaserver/blob/master/Publisher.tsx#L13

**Comment by rehamkhawajahere** [comment]
Thank you it's working fine now.
Can we set stream ID and live stream name using the client app? For example, we create 'WebSocket' on Ant Media Server using react native app.

**Comment by dipeshdulal** [comment]
I think you could do by calling RestAPI of ant media server from the client itself.  

https://antmedia.io/rest/#/BroadcastRestService/createBroadcast
