### ISSUE TITLE
Stream not publishing via IOS

### ISSUE THREAD

**Issue by rehamkhawajahere** [dipeshdulal/webrtc-antmediaserver#3]
On android, both publisher and viewer are working as expected but on IOS Publisher is not working though Viewer is working.

You get have-local-offer in logs but after that nothing, I also observed that at 1 time it got connected to Ant media Server for few secs and then disconnected.

Any lead on this?

**Comment by dipeshdulal** [comment]
Was working when I tested on iOS. 
Will try to re-run the code and check for the issue. 

Issue might be with some weird race-conditions. Can't say without checking for sure.
